<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">
			$(TargetFrameworks);net8.0-windows10.0.19041.0
		</TargetFrameworks>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
		<PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="coverlet.collector" Version="6.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="xunit" Version="2.5.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Typefout.Core.Data\Typefout.Core.Data.csproj" />
      <ProjectReference Include="..\Typefout.Core\Typefout.Core.csproj" />
      <ProjectReference Include="..\Typefout.App\Typefout.App.csproj" />
    </ItemGroup>

</Project>
